#!/usr/bin/env python3
"""Offline validation for the portable Vdbench UI project.

This validator intentionally uses only the Python standard library so it can run in
development environments that do not have Windows PowerShell available. It validates the
JSON contracts and renders representative Vdbench parameter files from the same catalog
shape used by the UI.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "config" / "parameter-catalog.json"
SETTINGS_PATH = ROOT / "config" / "default-settings.json"
LAUNCHER_PATH = ROOT / "Launch-VdbenchUI.bat"
FAKE_RUNNER_PATH = ROOT / "tools" / "FakeVdbench.ps1"
PACKAGE_SCRIPT_PATH = ROOT / "tools" / "Package-Portable.ps1"
SMOKE_SCRIPT_PATH = ROOT / "tools" / "Invoke-SmokeTest.ps1"
VERIFY_SCRIPT_PATH = ROOT / "tools" / "Verify-Portable.ps1"

REQUIRED_CATALOG_FIELDS = {
    "Key",
    "Section",
    "Label",
    "VdbenchName",
    "Line",
    "Type",
    "Default",
    "Options",
    "AppliesTo",
    "Required",
    "Help",
    "Example",
}

REQUIRED_SETTINGS = {
    "VdbenchRoot",
    "MasterVdbenchBat",
    "ReportsRoot",
    "RunMode",
    "ReadinessCheckerArguments",
    "SlaveShell",
}


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8-sig"))


def applies(definition: dict, test_kind: str) -> bool:
    target = definition["AppliesTo"]
    return target == "both" or (target == "raw" and test_kind == "Raw/block") or (
        target == "fs" and test_kind == "Filesystem"
    )


def default_profile(catalog: list[dict], name: str, test_kind: str) -> dict:
    params = {}
    for definition in catalog:
        value = str(definition.get("Default", ""))
        enabled = bool(definition.get("Required")) or bool(value.strip())
        params[definition["Key"]] = {"Enabled": enabled, "Value": value}
    return {
        "Name": name,
        "TestKind": test_kind,
        "Parameters": params,
        "AdvancedActive": "",
        "AdvancedDisabled": "",
    }


def param(profile: dict, key: str, default: str = "") -> str:
    item = profile["Parameters"].get(key)
    if not item:
        return default
    return str(item.get("Value") or default)


def enabled(profile: dict, key: str) -> bool:
    item = profile["Parameters"].get(key)
    return bool(item and item.get("Enabled"))


def add_params(parts: list[str], disabled: list[str], catalog: list[dict], profile: dict, line: str, test_kind: str):
    for definition in catalog:
        if definition["Line"] != line or not applies(definition, test_kind):
            continue
        key = definition["Key"]
        value = param(profile, key)
        if not value.strip():
            continue
        name = definition["VdbenchName"]
        if enabled(profile, key):
            if name == "openflags" and value == "none":
                continue
            parts.append(f"{name}={value}")
        else:
            disabled.append(f"* disabled: {name}={value} ({definition['Section']})")


def render_config(catalog: list[dict], settings: dict, profile: dict, slaves: list[dict] | None = None) -> str:
    test_kind = profile["TestKind"]
    distributed = bool(slaves)
    disabled: list[str] = []
    lines: list[str] = [
        "* Generated by offline validator",
        f"* Profile={profile['Name']}",
        f"* Mode={'Master/Slave distributed run' if distributed else 'Single local run'}",
        "",
    ]

    if distributed:
        host_defaults = ["hd=default"]
        if settings.get("SlaveShell"):
            host_defaults.append(f"shell={settings['SlaveShell']}")
        if settings.get("SlaveUser"):
            host_defaults.append(f"user={settings['SlaveUser']}")
        lines.append("* Host definitions")
        lines.append(",".join(host_defaults))
        for slave in slaves or []:
            system = slave.get("SshAlias") or slave["Host"]
            lines.append(f"hd={slave['Name']},system={system},vdbench={slave['VdbenchPath']}")
        lines.append("")

    if test_kind == "Raw/block":
        sd_name = param(profile, "storage.name", "sd1")
        wd_name = param(profile, "workload.name", "wd1")
        rd_name = param(profile, "run.name", "rd1")

        lines.append("* Storage definitions")
        if distributed:
            for slave in slaves or []:
                safe_name = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in slave["Name"])
                parts = [f"sd=sd_{safe_name}", f"host={slave['Name']}", f"lun={slave['TestTarget']}"]
                for definition in catalog:
                    if definition["Key"] == "storage.lun":
                        continue
                    if definition["Line"] == "storage" and applies(definition, test_kind):
                        add_params(parts, disabled, [definition], profile, "storage", test_kind)
                lines.append(",".join(parts))
        else:
            parts = [f"sd={sd_name}"]
            add_params(parts, disabled, catalog, profile, "storage", test_kind)
            lines.append(",".join(parts))
        lines.append("")

        parts = [f"wd={wd_name}", "sd=sd*" if distributed else f"sd={sd_name}"]
        add_params(parts, disabled, catalog, profile, "workload", test_kind)
        lines.extend(["* Workload definitions", ",".join(parts), ""])

        parts = [f"rd={rd_name}", f"wd={wd_name}"]
        add_params(parts, disabled, catalog, profile, "run", test_kind)
        lines.extend(["* Run definition", ",".join(parts)])
    else:
        fsd_name = param(profile, "fsd.name", "fsd1")
        fwd_name = param(profile, "fwd.name", "fwd1")
        rd_name = param(profile, "run.name", "rd1")

        lines.append("* Filesystem definitions")
        parts = [f"fsd={fsd_name}"]
        add_params(parts, disabled, catalog, profile, "fsd", test_kind)
        lines.extend([",".join(parts), ""])

        parts = [f"fwd={fwd_name}", f"fsd={fsd_name}"]
        add_params(parts, disabled, catalog, profile, "fwd", test_kind)
        lines.extend(["* Filesystem workload", ",".join(parts), ""])

        parts = [f"rd={rd_name}", f"fwd={fwd_name}"]
        add_params(parts, disabled, catalog, profile, "run", test_kind)
        lines.extend(["* Run definition", ",".join(parts)])

    if disabled:
        lines.extend(["", "* Disabled parameters preserved by UI", *disabled])
    return "\n".join(lines)


def validate_catalog(catalog: list[dict]):
    keys = set()
    for index, item in enumerate(catalog):
        missing = REQUIRED_CATALOG_FIELDS - set(item)
        assert not missing, f"catalog item {index} missing fields: {sorted(missing)}"
        key = item["Key"]
        assert key not in keys, f"duplicate catalog key: {key}"
        keys.add(key)
        assert item["Type"] in {"text", "dropdown"}, f"unsupported type for {key}: {item['Type']}"
        assert item["AppliesTo"] in {"both", "raw", "fs"}, f"bad AppliesTo for {key}: {item['AppliesTo']}"
        if item["Type"] == "dropdown":
            assert item["Options"], f"dropdown parameter has no options: {key}"


def main() -> int:
    settings = load_json(SETTINGS_PATH)
    catalog = load_json(CATALOG_PATH)

    validate_catalog(catalog)
    missing_settings = REQUIRED_SETTINGS - set(settings)
    assert not missing_settings, f"missing default settings: {sorted(missing_settings)}"
    assert "-STA" in LAUNCHER_PATH.read_text(encoding="utf-8"), "launcher must use -STA"
    ui_source = (ROOT / "src" / "VdbenchUI.ps1").read_text(encoding="utf-8")
    assert "$this" not in ui_source, "event handlers should use sender arguments, not $this"
    assert "param(" in ui_source and "[switch]$SelfTest" in ui_source
    assert "function Invoke-AppSelfTest" in ui_source
    assert "function Assert-SelfTestEquals" in ui_source
    assert "raw risk warning" in ui_source
    assert "ps1 runner quoted paths" in ui_source
    assert "function Write-JsonFile" in ui_source and "[switch]$AsArray" in ui_source
    assert "Write-JsonFile $script:SlavesPath $script:Slaves -AsArray" in ui_source
    assert "function Import-Settings" in ui_source
    assert "function Export-Settings" in ui_source
    assert "function Get-VdbenchProcessStartInfo" in ui_source
    assert "function New-ConfigOnlyRun" in ui_source
    assert "$script:KillRequested" in ui_source
    assert "function Duplicate-CurrentProfile" in ui_source
    assert "function Delete-SelectedProfile" in ui_source
    assert "function Import-Profile" in ui_source
    assert "function Export-CurrentProfile" in ui_source
    assert "function Test-AllSlaveConnections" in ui_source
    assert "function Check-AllSlaveReadiness" in ui_source
    assert "function Get-LocalTargetInventory" in ui_source
    assert "function Get-SlaveTargetInventory" in ui_source
    assert "function Convert-TargetInventoryOutput" in ui_source
    assert "function Pick-TargetForCurrentProfile" in ui_source
    assert "function Pick-TargetForSelectedSlave" in ui_source
    assert "Win32_DiskDrive" in ui_source and "Win32_Volume" in ui_source
    assert "ssh.exe" in ui_source
    assert "Pick target" in ui_source
    assert "target inventory parser count" in ui_source
    assert "function Import-SlaveInventory" in ui_source
    assert "function Export-SlaveInventory" in ui_source
    assert "function Export-SelectedRunBundle" in ui_source
    assert "Compress-Archive -Path $source" in ui_source
    assert "function Add-TargetRiskWarnings" in ui_source
    assert "function Get-RiskWarnings" in ui_source
    assert "Risk confirmation" in ui_source
    assert "function Test-RawDeviceTarget" in ui_source
    assert "RISK:" in ui_source
    assert "function Normalize-SlaveEntry" in ui_source
    assert "$Profile.Parameters = @($normalizedParameters)" in ui_source
    assert '/d /c "' in ui_source
    fake_runner = FAKE_RUNNER_PATH.read_text(encoding="utf-8")
    assert "Fake Vdbench runner" in fake_runner
    assert "interval" in fake_runner and "MB/sec" in fake_runner
    package_script = PACKAGE_SCRIPT_PATH.read_text(encoding="utf-8")
    assert "Compress-Archive -Path" in package_script
    assert "data" in package_script and "runs" in package_script
    smoke_script = SMOKE_SCRIPT_PATH.read_text(encoding="utf-8")
    assert "Fake Vdbench completed successfully" in smoke_script
    assert "data\\smoke" in smoke_script
    verify_script = VERIFY_SCRIPT_PATH.read_text(encoding="utf-8")
    assert "Project validation" in verify_script
    assert "Fake-runner smoke test" in verify_script
    assert "Portable package inspection" in verify_script
    assert "tools\\Verify-Portable.ps1" in verify_script

    raw = default_profile(catalog, "Offline-Raw", "Raw/block")
    raw["Parameters"]["storage.dedupratio"]["Enabled"] = False
    raw["Parameters"]["storage.dedupratio"]["Value"] = "2"
    raw_config = render_config(catalog, settings, raw)
    assert "sd=sd1,lun=C:\\vdbench\\testfile.dat" in raw_config
    assert "wd=wd1,sd=sd1,xfersize=4k,rdpct=70,seekpct=100" in raw_config
    assert "rd=rd1,wd=wd1,elapsed=300,warmup=30,interval=1,iorate=max" in raw_config
    assert "* disabled: dedupratio=2" in raw_config

    slave_config = render_config(
        catalog,
        settings,
        raw,
        [
            {
                "Name": "test-001",
                "Host": "10.0.0.11",
                "SshAlias": "test-001",
                "VdbenchPath": "/opt/vdbench",
                "TestTarget": "/dev/sdb",
            }
        ],
    )
    assert "hd=default,shell=ssh" in slave_config
    assert "hd=test-001,system=test-001,vdbench=/opt/vdbench" in slave_config
    assert "sd=sd_test_001,host=test-001,lun=/dev/sdb" in slave_config
    assert "wd=wd1,sd=sd*" in slave_config

    fs = default_profile(catalog, "Offline-FS", "Filesystem")
    fs_config = render_config(catalog, settings, fs)
    assert "fsd=fsd1,anchor=C:\\vdbench\\fs_test" in fs_config
    assert "fwd=fwd1,fsd=fsd1,operation=read" in fs_config
    assert "rd=rd1,fwd=fwd1,elapsed=300,warmup=30,interval=1,fwdrate=max,format=no" in fs_config

    print("offline validation ok")
    print(f"catalog parameters: {len(catalog)}")
    print("sample configs: raw local, raw distributed, filesystem local")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
